examples/README.md, examples/cat.fetch, examples/cat/lift.linux-aarch64.json, examples/cat/lift.linux-x86_64.json, examples/cat/lift.macos-aarch64.json, examples/cat/lift.macos-x86_64.json, examples/cat/lift.windows-x86_64.json, examples/cat/test.sh, examples/run.sh, jump/src/lift.rs
Previously an incomplete scie assembly could be spoofed at runtime by placing maliciously crafted files relative to it.
Fixes #26
=> Harden scie-jump runtime validation.

examples/python/test.sh, jump/src/installer.rs
Previously the blob parent directory was locked instead of the blob
itself and this could lead to the blob not being re-unpacked if it
was deleted after 1st unpack.
A previously failing test of this is added to the python example where
the Pants binding command does, in fact, delete the pants.pex blob.
=> Fix blob locks.

examples/load/get.sh, examples/load/lift.linux-aarch64.json, examples/load/lift.linux-x86_64.json, examples/load/lift.macos-aarch64.json, examples/load/lift.macos-x86_64.json, examples/load/lift.windows-x86_64.json, examples/load/test.sh, jump/src/atomic.rs, jump/src/config.rs, jump/src/context.rs, jump/src/installer.rs, jump/src/lib.rs, jump/src/lift.rs, jump/src/process.rs, src/boot/pack.rs
Files can now either be embedded in a scie or else loaded at runtime via
a binding command that takes the filename to load as an argument and
produces the file content on stdout. Hashing and size checking are still
performed by the installer.
An example is added that assumes `curl`, `jq` and `bash` are present on
the host for doing loading from the internet.
Closes #19
=> Support files that are lazy loaded at runtime.

CHANGES.md, Cargo.lock, Cargo.toml, examples/.gitignore, examples/ptex/lift.linux-aarch64.json, examples/ptex/lift.linux-x86_64.json, examples/ptex/lift.macos-aarch64.json, examples/ptex/lift.macos-x86_64.json, examples/ptex/lift.windows-x86_64.json, examples/ptex/test.sh, jump/Cargo.toml, jump/src/installer.rs
Previously a scie utilizing a scie-tote would extract that scie-tote on
every run whether or not the file entries of the scie-tote had already
been extracted themselves. Fix this and add a ptex example which is
where this issue was 1st discovered.
Fixes #43
=> Fix eager scie-tote extraction.

README.md, docs/packaging.md, examples/cat/lift.linux-aarch64.json, examples/cat/lift.linux-x86_64.json, examples/cat/lift.macos-aarch64.json, examples/cat/lift.macos-x86_64.json, examples/cat/lift.windows-x86_64.json, examples/load/lift.linux-aarch64.json, examples/load/lift.linux-x86_64.json, examples/load/lift.macos-aarch64.json, examples/load/lift.macos-x86_64.json, examples/load/lift.windows-x86_64.json, examples/load/test.sh, examples/ptex/test.sh, jump/README.md, jump/src/config.rs, jump/src/context.rs, jump/src/lift.rs
=> Use standard cache directories for `nce` cache.

.cargo/config.toml, .circleci/config.yml, .github/workflows/ci.yml, .github/workflows/release.yml, CONTRIBUTING.md, Cargo.toml, README.md
Fix configuration file formatting, build docs, Circle CI testing
(currently noops / tests just the root package and not `jump`) for the
aarch64 build and minimize docker alpine based builds by removing
unneeded extra package adds.
=> Cleanup after switch to musl for Linux.

examples/node/test.sh, jump/src/lib.rs, jump/src/lift.rs, src/boot.rs, src/main.rs
For the `busybox` binary these are `busybox --install (-s) dest_dir`
and `busybox --list`.
This provides an ergonomic way to ship a tool-kit.
Instead of the clunky `SCIE_BOOT=tool toolkit ...` on each and every
tool invocation you can `SCIE=install toolkit ~/bin` one time and have 
standard discoverability and ergonomics for all
`scie.lift.boot.commands`.
=> Support SCIE={list,install} BusyBox-alikes.

CHANGES.md, Cargo.lock, Cargo.toml, docs/packaging.md, jump/Cargo.toml, jump/src/archive.rs, jump/src/context.rs, jump/src/fingerprint.rs, jump/src/installer.rs, jump/src/lib.rs, jump/src/lift.rs, jump/src/placeholders.rs, jump/src/process.rs, src/boot/pack.rs
Support is added for:
+ New placeholders:
- `{scie.base}`: The current `SCIE_BASE`.
- `{scie.files.<name>}`: Another way to say `{<name>}`.
- `{scie.files.<name>:hash}`: The sha256 hash of the named file.
- `{scie.bindings.<name>:<key>}`: The output named key of the named
binding.
For the last, bindings have access to a `SCIE_BINDING_ENV` environment
variable pointing to a file they can write `<key>=<value>` lines to to
propagate binding information via the `{scie.bindings.<name>:<key>}`
placeholder.
+ Environment sensitive bindings:
Binding commands are now locked based on the content hash of their
env, exe and args. This allows for binding commands that are still
guaranteed to run only once, but once for each unique context.
=> Various improvements fleshed out by scie-pants.

CHANGES.md, Cargo.lock, Cargo.toml, jump/Cargo.toml, jump/src/context.rs
This makes it easier to implement a command that re-executes the `SCIE` itself.
=> Clear `SCIE_BOOT` env var when redirecting via it.

examples/ptex/test.sh, src/boot/split.rs
Previousy, splitting a gouged out scie failed; now it round-trips byte-wise identical.
Fixes #62
=> Fix SCIE=split to work with ptex.

CHANGES.md, Cargo.lock, Cargo.toml, docs/packaging.md, examples/node/test.sh, jump/Cargo.toml, jump/src/lib.rs, src/boot.rs, src/boot/pack.rs
This complements the existing `SCIE` env var and allows detection of scies that are symlinked.
=> Expose a `SCIE_ARGV0` env var to scies.

CHANGES.md, Cargo.lock, Cargo.toml, docs/packaging.md, examples/python/lift.linux-x86_64.json, examples/python/lift.macos-x86_64.json, examples/python/test.sh, jump/Cargo.toml, jump/src/cmd_env.rs, jump/src/config.rs, jump/src/context.rs, jump/src/lib.rs
This is needed by https://github.com/a-scie/lift for interpreter group
selection support and is otherwise a reasonable thing to expect to have
worked.
=> Support `{scie.env.*}` referring to cmd env values.

.circleci/config.yml, .github/workflows/ci.yml, .github/workflows/release.yml, rust-toolchain
https://blog.rust-lang.org/2023/04/20/Rust-1.69.0.html
=> Upgrade to Rust 1.69.0.

CHANGES.md, Cargo.lock, Cargo.toml, examples/python/lift.linux-x86_64.json, examples/python/lift.macos-x86_64.json, examples/python/test.sh, jump/Cargo.toml, jump/src/process.rs
Previously the scie-jump boot would crash when a manifest requested
regex removals and the ambient environment contained non-utf8 entries.
Fixes #105
=> Fix regex env removal vs. non-utf8 env entries.

.cargo/config.toml, .circleci/config.yml, .github/workflows/ci.yml, .github/workflows/release.yml, Cargo.lock, jump/Cargo.toml, jump/src/process.rs, rust-toolchain
https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html
Since the sparse index protocol is now default, kill the explicit
configuration of that.
Also use the now stabilized std::sync::OnceLock instead of the once_cell
crate in tests.
Closes #108
=> Upgrade to Rust 1.70.0.

Cargo.lock, Cargo.toml
Dependabot tried and failed since the features structure has changed (
see: https://github.com/a-scie/jump/pull/132). Explicitly list the
features we need allowing upgrade to 0.27.1 (latest) and future nix
versions.
=> Upgrade nix.

CHANGES.md, Cargo.lock, Cargo.toml, docs/packaging.md, jump/Cargo.toml, jump/src/cmd_env.rs, jump/src/config.rs, jump/src/context.rs, jump/src/installer.rs, jump/src/lift.rs, jump/src/placeholders.rs
Both the lift manifest `scie.lift.base` field and the `SCIE_BASE` env
var now have their values expanded, accepting all placeholders except
for the `{scie.lift}` which depends on the fully evaluated value of the
scie base.
In order to make OS-convention-friendly values feasible, a new
`{scie.user.cache_dir=<fallback>}` placeholder is added that expands to
the OS-appropriate user cache dir when defined and `<fallback>` when
not.
=> Add support for scie base value placeholders.

Cargo.lock, jump/Cargo.toml, jump/src/lib.rs
These 2 forks appear to be the blessed successors.
These unmaintained crate dependencies were revelead by a cargo audit run:
```
$ cargo audit
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 570 security advisories (from /home/jsirois/.cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (140 crate dependencies)
Crate:     dotenv
Version:   0.15.0
Warning:   unmaintained
Title:     dotenv is Unmaintained
Date:      2021-12-24
ID:        RUSTSEC-2021-0141
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0141
Dependency tree:
dotenv 0.15.0
└── jump 0.12.0
├── scie-jump 0.12.0
└── package 0.2.0
Crate:     memmap
Version:   0.7.0
Warning:   unmaintained
Title:     memmap is unmaintained
Date:      2020-12-02
ID: …
```
=> Use maintained forks of dotenv(->y) & memmap(->2).

CHANGES.md, Cargo.lock, Cargo.toml, docs/packaging.md, examples/busybox/default-only-lift.linux-x86_64.json, examples/busybox/lift.linux-x86_64.json, examples/busybox/mixed-no-default-desc-lift.linux-x86_64.json, examples/busybox/mixed-with-default-desc-lift.linux-x86_64.json, examples/busybox/named-commands-only-no-desc-lift.linux-x86_64.json, examples/busybox/named-commands-only-with-desc-lift.linux-x86_64.json, examples/busybox/test.sh, jump/Cargo.toml, jump/src/context.rs, jump/src/lib.rs, src/boot.rs
This fixes the error messages displayed when a boot command could not be
found by both differentiating the cases where this can occur with their
own specialized messages and improving the guidance in general.
As part of these messaging fixes, support for hiding commands is added
by omitting descriptions for those named commands you wish to hide from
the boot failure help screen.
Fixes #143
Fixes #144
=> Improve the select boot failure help.

.github/workflows/ci.yml, .github/workflows/release.yml, rust-toolchain
The release annoucement is here:
https://blog.rust-lang.org/2023/09/19/Rust-1.72.1.html
=> Upgrade Rust to 1.72.1.

CHANGES.md, Cargo.lock, Cargo.toml, docs/packaging.md, jump/Cargo.toml, jump/src/comparable_regex.rs, jump/src/process.rs
=> Allow regex removal of non-utf8 env var names.

.github/workflows/ci.yml
This passes `--locked` to the first interesting cargo invocation, to ensure that the `Cargo.lock` file is up to date with `Cargo.toml`. Without this,  if there's been changes to `Cargo.toml` and the user hasn't run a cargo command locally afterwards, the invocation might change the `Cargo.lock` file (e.g. bump versions, add packages) and thus CI runs with an unexpected configuration, that's not recorded in the repo.
(This came up in https://github.com/pantsbuild/scie-pants/pull/290 and I thought to check other Rust repos that are tangentially related.)
=> Require Cargo.lock matches Cargo.toml in CI

.circleci/config.yml, jump/src/comparable_regex.rs, rust-toolchain
https://blog.rust-lang.org/2023/10/05/Rust-1.73.0.html
=> Upgrade to Rust 1.73.0.

CHANGES.md, Cargo.lock, Cargo.toml, examples/load/test.sh, jump/Cargo.toml, jump/src/lib.rs
Previously, when requesting `load_dotenv` for a scie, the scie would
silently skip all `.env` file lines after any line with a syntax error.
Fixes #163
=> Propagate errors loading `.env` files.

.circleci/config.yml, .github/workflows/ci.yml, CHANGES.md, Cargo.lock, Cargo.toml, jump/Cargo.toml
Previously liblzma was dynamically linked (to a homebrew version).
Fixes #172
=> Fix our xz2 crate configuration to enable static linking.

.circleci/config.yml, .github/workflows/ci.yml
These skips were added in #173 to work around this issue:
https://github.com/rust-lang/rustfmt/issues/5964
It has been resolved; so formatting should now work on all architectures.
Fixes #174
=> Undo aarch64 rustfmt skips.

CHANGES.md, Cargo.lock, Cargo.toml, docs/packaging.md, examples/load/test.sh, jump/Cargo.toml, jump/src/lib.rs
Switch from the dotenvy crate to dotenvs to achieve this. A patched
version is used to ensure we maintain support for hard failure when
invalid `.env` files are read.
Fixes #166
Fixes #167
=> Add support for expanding `.env` quoted values.

.circleci/config.yml, .github/workflows/ci.yml, .github/workflows/release.yml, rust-toolchain
https://blog.rust-lang.org/2024/02/08/Rust-1.76.0.html
=> Upgrade to Rust 1.76.0.

jump/src/lib.rs
The reference to `--path` was in error, it should have been
`-sj|--jump|--scie-jump`.
=> Fix `boot-pack` help.

.github/workflows/audit.yml, .github/workflows/ci.yml, .github/workflows/release.yml
This eliminates node16 warnings / prepares for the spring when node16
goes away.
=> Upgrade actions.

.github/workflows/audit.yml
The previous incantation both kept cargo-audit back and did not use its
lock. This was the worst of both worlds and led to an audit job break.
=> Stabilize cargo audit.

.circleci/config.yml, .github/workflows/ci.yml, .github/workflows/release.yml, CHANGES.md, Cargo.lock, Cargo.toml, rust-toolchain
The 1.78 release bumps the minimum supported Windows version to Windows
10; so we bump our major version to indicate the breaking change, and,
~1.5 years after the first public release, semi-offcially declare
stability given some level of battle testing.
As a point of reference, Microsoft support for Windows 8 ended on
January 12, 2016, and support for Windows 8.1 ended on
January 10, 2023; so `scie-jump` likely only ever could have had
Windows 8.1 users.
https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html
=> Upgrade Rust to 1.78.0.

.circleci/config.yml, .github/workflows/ci.yml, .github/workflows/release.yml, rust-toolchain
https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html
=> Upgrade to Rust 1.79.0.

.github/workflows/ci.yml, .github/workflows/release.yml, rust-toolchain
https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html
=> Upgrade to Rust 1.80.0.

docs/packaging.md
The `examples/cat/test.sh` test gets this right (or it would fail!), but
the docs had this wrong.
=> Fix `cat` packaging docs.

.github/workflows/ci.yml, .github/workflows/release.yml, rust-toolchain
https://blog.rust-lang.org/2024/08/08/Rust-1.80.1.html
=> Upgrade to Rust 1.80.1.

.github/workflows/ci.yml, .github/workflows/release.yml, CHANGES.md, Cargo.lock, Cargo.toml, examples/cat/lift.windows-aarch64.json, examples/java/lift.windows-aarch64.json, examples/load/lift.windows-aarch64.json, examples/node/cowsay-lift.windows-aarch64.json, examples/node/lift.windows-aarch64.json, examples/ptex/lift.windows-aarch64.json, examples/run.sh
Fixup arch detection in `examples/run.sh` to handle Git for Windows
(and thus bash, etc.) being x86-64 still: use PowerShell to determine
the true arch.
=> Add a Windows ARM64 release.

.github/workflows/ci.yml, .github/workflows/release.yml, rust-toolchain
https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html
=> Upgrade to Rust 1.81.0.

.github/workflows/ci.yml, .github/workflows/release.yml, jump/src/context.rs, rust-toolchain
https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html
=> Upgrade to Rust 1.82.0.

.github/workflows/ci.yml, .github/workflows/release.yml, jump/src/config.rs, rust-toolchain
https://blog.rust-lang.org/2024/11/28/Rust-1.83.0.html
=> Upgrade to Rust 1.83.0.

.github/workflows/ci.yml, .github/workflows/release.yml, CHANGES.md, Cargo.lock, Cargo.toml, docs/packaging.md, examples/README.md, examples/busybox/default-only-lift.linux-s390x.json, examples/busybox/lift.linux-s390x.json, examples/busybox/mixed-no-default-desc-lift.linux-s390x.json, examples/busybox/mixed-with-default-desc-lift.linux-s390x.json, examples/busybox/named-commands-only-no-desc-lift.linux-s390x.json, examples/busybox/named-commands-only-with-desc-lift.linux-s390x.json, examples/run.sh
Mainframe Linux support has been on my list.
=> Add support for Linux s390x.

rust-toolchain
Announcement: https://blog.rust-lang.org/2025/01/09/Rust-1.84.0.html
=> Upgrade to Rust 1.84.0.

rust-toolchain
Announcement: https://blog.rust-lang.org/2025/01/30/Rust-1.84.1.html
=> Upgrade to Rust 1.84.1.

Cargo.lock, Cargo.toml, rust-toolchain, src/boot/pack.rs
Announcement: https://blog.rust-lang.org/2025/02/20/Rust-1.85.0.html
Also `cargo update -p ctor` to get past the warning detailed here:
https://github.com/mmastrac/rust-ctor/issues/309
=> Upgrade to Rust 1.85.0 / 2024 edition.

CHANGES.md, Cargo.lock, Cargo.toml, examples/cat/test.sh, examples/load/test.sh, jump/src/archive.rs, jump/src/config.rs, jump/src/context.rs, jump/src/installer.rs, jump/src/lib.rs, package/Cargo.toml, src/boot.rs, src/boot/pack.rs, src/boot/split.rs
The `SCIE=split` scie built-in command now supports listing a subset of
files to split out by passing them after `--`; e.g.:
`SCIE=split my-scie -- scie-jump` splits out just the scie-jump. For
discovery of what is available to split out, you can now run the split in
dry-run mode to get a preview of the files that would be split out
including their unpacked sizes.
Using `examples/node`:
```console
:; SCIE=split ./cowsay.js --dry-run
Would extract:
[destination file] [extracted size in bytes] [type] ([alt key for file])?
-------------------------------------------------------------------------
scie-jump 2042848 executable
node-v18.12.0-linux-x64.tar.xz 23692504 archive (node)
node_modules 1114908 directory
lift.json 982 blob
```
=> Support splitting out a subset of files.

Cargo.lock, jump/Cargo.toml, jump/src/cmd_env.rs, jump/src/context.rs, jump/src/installer.rs, jump/src/lib.rs, jump/src/lift.rs, jump/src/placeholders.rs, jump/src/process.rs, package/src/main.rs, rust-toolchain, src/boot/split.rs, src/main.rs
Announcement: https://blog.rust-lang.org/2025/03/18/Rust-1.85.1.html
The jump crate was left back on the 2021 edition during the 1.85.0
upgrade since env var mutation is now unsafe and the changes to avoid
these mutations are a bit extensive. This change bites that bullet.
=> Upgrade rust to 1.85.1 / jump to 2025 edition.

rust-toolchain
Announcement: https://blog.rust-lang.org/2025/04/03/Rust-1.86.0.html
=> Upgrade to Rust 1.86.0

CHANGES.md, Cargo.lock, Cargo.toml, docs/packaging.md, jump/src/cmd_env.rs, jump/src/context.rs, jump/src/lib.rs, jump/src/placeholders.rs
Although the `SCIE` and `SCIE_ARGV0` env vars were already populated 
for scies to observe at runtime, they were not previously available for
substitution in placeholders at boot time.
Motivated by https://github.com/pex-tool/pex/issues/2733, but a glaring
hole on its own.
=> Support `scie.argv0` & `scie.env.SCIE{,_ARGV0}`.

jump/src/placeholders.rs, rust-toolchain
Release announcement: https://blog.rust-lang.org/2025/06/26/Rust-1.88.0/
=> Upgrade to Rust 1.88.0.

rust-toolchain
https://blog.rust-lang.org/2025/09/18/Rust-1.90.0/
=> Upgrade Rust to 1.90.0.
